CREATE DATABASE QL_TRUONGHOC

USE QL_TRUONGHOC
GO

DROP DATABASE QL_TRUONGHOC


------TẠO BẢNG-----
CREATE TABLE KHOA
(
	MaKhoa CHAR(4) PRIMARY KEY,
	TenKhoa NVARCHAR(100),
	NamThanhLap INT
)
CREATE TABLE KHOAHOC
(
	MaKhoaHoc CHAR(4) PRIMARY KEY,
	NamBatDau INT,
	NamKetThuc INT
)
CREATE TABLE CHUONGTRINH
(
	MaCT CHAR(2) PRIMARY KEY,
	TenCT NVARCHAR(MAX)
)
CREATE TABLE LOP
(
	MaLop CHAR(7) PRIMARY KEY,
	TenLop NVARCHAR(100),
	MaKhoa CHAR(4) FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa),
	MaKhoaHoc CHAR(4) FOREIGN KEY (MaKhoaHoc) REFERENCES KHOAHOC(MaKhoaHoc),
	MaCT CHAR(2) FOREIGN KEY (MaCT) REFERENCES CHUONGTRINH(MaCT),
	STT INT
)

CREATE TABLE MONHOC
(
	MaMH CHAR(4) PRIMARY KEY,
	TenMH NVARCHAR(100),
	MaKhoa CHAR(4) FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
)
CREATE TABLE SINHVIEN
(
	MaSV CHAR(4) PRIMARY KEY,
	TenSV NVARCHAR(100),
	SDT CHAR(10),
	DiaChi NVARCHAR(MAX),
	Email VARCHAR(MAX),
	HINH NVARCHAR(MAX),
	NamSinh INT,
	MatKhau CHAR(10),
	MaLop CHAR(7) FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
)
CREATE TABLE GIAOVIEN
(
	MaGV CHAR(4) PRIMARY KEY,
	TenGV NVARCHAR(MAX),
	MatKhau CHAR(10),
	MaMH CHAR(4) FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
)
CREATE TABLE KETQUA
(
	MaSV CHAR(4),
	MaMH CHAR(4),
	LanThi INT,
	Diem FLOAT,
	PRIMARY KEY(MaSV,MaMH,LanThi),
	FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH),
	FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV)
)
CREATE TABLE GIANGKHOA
(
	MaCT CHAR(2) FOREIGN KEY (MaCT) REFERENCES CHUONGTRINH(MaCT),
	MaKhoa CHAR(4) FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa),
	MaMH CHAR(4) FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH),
	NamHoc INT,
	HocKy INT,
	SoTietLyThuyet INT,
	SoTietThucHanh INT,
	SoTC INT,
	PRIMARY KEY(MaCT,MaKhoa,MaMH)
)

CREATE TABLE TINTUC
(
	MaTin CHAR(4) PRIMARY KEY,
	TieuDe NVARCHAR(MAX),
	NoiDung NVARCHAR(MAX),
	Hinh NVARCHAR(MAX),
	Ngay DATE
)
------NHẬP LIỆU------
SELECT * FROM KHOA
SELECT * FROM KHOAHOC
SELECT * FROM CHUONGTRINH
SELECT * FROM MONHOC
SELECT * FROM GIAOVIEN
SELECT * FROM LOP
SELECT * FROM SINHVIEN
SELECT * FROM KETQUA
SELECT * FROM GIANGKHOA


